name: place_picker
description: Place picker fully written in dart for Flutter. Comes with autocomplete suggestions and nearby locations list. Localization too.
version: 0.9.19
homepage: https://github.com/blackmann/locationpicker

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  google_maps_flutter: ^2.1.1
  location: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true